const activeTeams = [
    "Montréal Canadiens",
    "Buffalo Sabres",
    "New York Islanders",
    "San Jose Sharks",
    "Columbus Blue Jackets",
    "Pittsburgh Penguins",
    "Florida Panthers",
    "Carolina Hurricanes",
    "Vegas Golden Knights",
    "Dallas Stars",
    "Winnipeg Jets",
    "Tampa Bay Lightning",
    "Utah Hockey Club",
    "Nashville Predators",
    "Philadelphia Flyers",
    "New Jersey Devils",
    "Ottawa Senators",
    "Colorado Avalanche",
    "Seattle Kraken",
    "Washington Capitals",
    "Anaheim Ducks",
    "Los Angeles Kings",
    "Vancouver Canucks",
    "Minnesota Wild",
    "Toronto Maple Leafs",
    "New York Rangers",
    "Edmonton Oilers",
    "Calgary Flames",
    "Boston Bruins",
    "St. Louis Blues",
    "Chicago Blackhawks",
    "Detroit Red Wings"
];

export function isActiveTeam(teamName: string): boolean { 
    return activeTeams.includes(teamName)
}

export enum ActiveNhlTeam {
    MontrealCanadiens = "Montréal Canadiens",
    BuffaloSabres = "Buffalo Sabres",
    NewYorkIslanders = "New York Islanders",
    SanJoseSharks = "San Jose Sharks",
    ColumbusBlueJackets = "Columbus Blue Jackets",
    PittsburghPenguins = "Pittsburgh Penguins",
    FloridaPanthers = "Florida Panthers",
    CarolinaHurricanes = "Carolina Hurricanes",
    VegasGoldenKnights = "Vegas Golden Knights",
    DallasStars = "Dallas Stars",
    WinnipegJets = "Winnipeg Jets",
    TampaBayLightning = "Tampa Bay Lightning",
    UtahHockeyClub = "Utah Hockey Club",
    NashvillePredators = "Nashville Predators",
    PhiladelphiaFlyers = "Philadelphia Flyers",
    NewJerseyDevils = "New Jersey Devils",
    OttawaSenators = "Ottawa Senators",
    ColoradoAvalanche = "Colorado Avalanche",
    SeattleKraken = "Seattle Kraken",
    WashingtonCapitals = "Washington Capitals",
    AnaheimDucks = "Anaheim Ducks",
    LosAngelesKings = "Los Angeles Kings",
    VancouverCanucks = "Vancouver Canucks",
    MinnesotaWild = "Minnesota Wild",
    TorontoMapleLeafs = "Toronto Maple Leafs",
    NewYorkRangers = "New York Rangers",
    EdmontonOilers = "Edmonton Oilers",
    CalgaryFlames = "Calgary Flames",
    BostonBruins = "Boston Bruins",
    StLouisBlues = "St. Louis Blues",
    ChicagoBlackhawks = "Chicago Blackhawks",
    DetroitRedWings = "Detroit Red Wings"
}

export enum InactiveNhlTeams { 
    QuebecNordiques = "Quebec Nordiques",
    TorontoStPatricks = "Toronto St. Patricks",
    OaklandSeals = "Oakland Seals",
    KansasCityScouts = "Kansas City Scouts",
    OttawaSenators1917 = "Ottawa Senators (1917)",
    ToBeDetermined = "To be determined",
    AtlantaThrashers = "Atlanta Thrashers",
    StLouisEagles = "St. Louis Eagles",
    WinnipegJets1979 = "Winnipeg Jets (1979)",
    QuebecBulldogs = "Quebec Bulldogs",
    ArizonaCoyotes = "Arizona Coyotes",
    PhoenixCoyotes = "Phoenix Coyotes",
    MontrealWanderers = "Montreal Wanderers",
    PhiladelphiaQuakers = "Philadelphia Quakers",
    HamiltonTigers = "Hamilton Tigers",
    DetroitCougars = "Detroit Cougars",
    ColoradoRockies = "Colorado Rockies",
    PittsburghPirates = "Pittsburgh Pirates",
    HartfordWhalers = "Hartford Whalers",
    NewYorkAmericans = "New York Americans",
    MinnesotaNorthStars = "Minnesota North Stars",
    NHL = "NHL",
    MontrealMaroons = "Montreal Maroons",
    ClevelandBarons = "Cleveland Barons",
    BrooklynAmericans = "Brooklyn Americans",
    DetroitFalcons = "Detroit Falcons",
    CaliforniaGoldenSeals = "California Golden Seals",
    AtlantaFlames = "Atlanta Flames",
    TorontoArenas = "Toronto Arenas",
}
export enum ActiveNhlTeamAbbreviations {
    MontrealCanadiens = "MTL",
    BuffaloSabres = "BUF",
    NewYorkIslanders = "NYI",
    SanJoseSharks = "SJS",
    ColumbusBlueJackets = "CBJ",
    PittsburghPenguins = "PIT",
    FloridaPanthers = "FLA",
    CarolinaHurricanes = "CAR",
    VegasGoldenKnights = "VGK",
    DallasStars = "DAL",
    WinnipegJets = "WPG",
    TampaBayLightning = "TBL",
    UtahHockeyClub = "UTA",
    NashvillePredators = "NSH",
    PhiladelphiaFlyers = "PHI",
    NewJerseyDevils = "NJD",
    OttawaSenators = "OTT",
    ColoradoAvalanche = "COL",
    SeattleKraken = "SEA",
    WashingtonCapitals = "WSH",
    AnaheimDucks = "ANA",
    LosAngelesKings = "LAK",
    VancouverCanucks = "VAN",
    MinnesotaWild = "MIN",
    TorontoMapleLeafs = "TOR",
    NewYorkRangers = "NYR",
    EdmontonOilers = "EDM",
    CalgaryFlames = "CGY",
    BostonBruins = "BOS",
    StLouisBlues = "STL",
    ChicagoBlackhawks = "CHI",
    DetroitRedWings = "DET"
}
