/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TeamsIndexImport } from './routes/teams/index'
import { Route as TeamsTeamSeasonImport } from './routes/teams/$team.$season'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsIndexRoute = TeamsIndexImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsTeamSeasonRoute = TeamsTeamSeasonImport.update({
  id: '/teams/$team/$season',
  path: '/teams/$team/$season',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/$team/$season': {
      id: '/teams/$team/$season'
      path: '/teams/$team/$season'
      fullPath: '/teams/$team/$season'
      preLoaderRoute: typeof TeamsTeamSeasonImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teams': typeof TeamsIndexRoute
  '/teams/$team/$season': typeof TeamsTeamSeasonRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teams': typeof TeamsIndexRoute
  '/teams/$team/$season': typeof TeamsTeamSeasonRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/teams/$team/$season': typeof TeamsTeamSeasonRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/teams' | '/teams/$team/$season'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/teams' | '/teams/$team/$season'
  id: '__root__' | '/' | '/teams/' | '/teams/$team/$season'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TeamsTeamSeasonRoute: typeof TeamsTeamSeasonRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TeamsTeamSeasonRoute: TeamsTeamSeasonRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/teams/",
        "/teams/$team/$season"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/teams/": {
      "filePath": "teams/index.tsx"
    },
    "/teams/$team/$season": {
      "filePath": "teams/$team.$season.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
